import type { NextPage } from "next";
import Head from "next/head";
import { SetStateAction, useEffect,useState } from "react";
import styled from "styled-components";
import { PokemonClient } from 'pokenode-ts';
import { trpc } from '../utils/trpc';


const TitleContainer = styled.div`
  text-align: center;
`;
const ContentContainer = styled.div`
  display: flex;
  justify-content: center;
  column-gap: 2rem;
  div {
    text-align: center;
    width: 200px;
    height: 200px;
    background-color: black;
    display:flex;
    align-items:center;
    p{
      margin: 0 auto;
    }
  }
`;

const Separator = styled.div`
  height: 100px;
`

const Home: NextPage = () => {
  // const [data, setData] = useState()

  // useEffect( () => {
   
  //   const getPokemon = async () => {
  //     const api = new PokemonClient();
    
  //     // const data: SetStateAction<Array> = await api
  //     //   .getPokemonByName('luxray')
  //     //   .then((data) => console.log(data.name)) // will output "Luxray"
  //     //   .catch((error) => console.error(error));
      
  //     //   setData(data)
  //   }

  //   getPokemon;
  // }, [])

  const hello = trpc.useQuery(['hello', { text: 'Juan' }]);
  if (!hello.data) {
    return <div>Loading...</div>;
  }

  // console.log(data)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <TitleContainer>
          <h1>Which is the cuitest pokemon?</h1>
          <p>{hello.data.greeting}</p>
        </TitleContainer>
        <Separator />
        <ContentContainer>
          <div>
            <p>Pokemon 1</p>
          </div>
          <div>
            <p>vs</p>
          </div>
          <div>
            <p>Pokemon 2</p>
          </div>
        </ContentContainer>
      </main>
    </div>
  );
};

export default Home;
